### ISSUE TITLE
Locale issues

### ISSUE THREAD

**Issue by mrb** [filib/codeclimate-shellcheck#42]
@filib  - Analyzing the repo for git (https://github.com/git/git) I came across an error:

```
Michaels-MBP-4:git mrb$ codeclimate analyze --dev contrib/mw-to-git/t/t9363-mw-to-git-export-import.sh
Starting analysis
Running shellcheck: Done!
error: (CC::Analyzer::Engine::EngineFailure) engine shellcheck failed with status 1 and stderr 
engine: contrib/mw-to-git/t/t9363-mw-to-git-export-import.sh: hGetContents: invalid argument (invalid byte sequence)
engine: thread blocked indefinitely in an MVar operation
```

It looks like from this issue https://github.com/elm-lang/elm-make/issues/33 that we probably have to set the `LOCALE` to some flavor of UTF-8. Any thoughts on the best way to handle this?

**Comment by filib** [comment]
@mrb I'm not going be able to take a look at this one today and it seems like we keep missing each other due to the time difference.

I think you're right, it does look like it could be fixed by specifying the locale. I'm guessing we'll need to find out the best way to do that on busybox - I'm not sure off hand.

**Comment by mrb** [comment]
@filib No worries! I tried a few things that failed.

**Comment by filib** [comment]
May also be relevant https://github.com/koalaman/shellcheck/issues/324

**Comment by filib** [comment]
:tada: :+1:
